name: cicak-deploy
on:
  push:
    branches:
      - "main"
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      run: |
        echo ${{secrets.CICAK_SSH_KEY}} >> ~/.ssh/ssh_key
        cat ~/.ssh/ssh_key
        ssh -o StrictHostKeyChecking=no -p 2288 -i ~/.ssh/ssh_key cicak@103.65.236.98\
        echo "Hello World"